### ISSUE TITLE
table ChiNhanh

### ISSUE THREAD

**Issue by 4azuo** [15HCB2-Wind/DoAn-PT-HTTT-HD#15]

**Comment by vstrunghieu** [comment]
Đã xong DataAccess + Data Service cho ChiNhanh

**Comment by vstrunghieu** [comment]
Upload len GitHub, chuyen trang thai Issue sang close

**Comment by 4azuo** [comment]
chỉ leader mới close thôi, chú kéo qua done là dc, có gì t xem lại rùi mới close hoặc báo lỗi để làm lại

**Comment by 4azuo** [comment]
ok, closed!
