### ISSUE TITLE
table ChiTietBaoCaoTinhTrangBo

### ISSUE THREAD

**Issue by 4azuo** [15HCB2-Wind/DoAn-PT-HTTT-HD#16]

**Comment by vstrunghieu** [comment]
Đã xong DataAccess + Data Service cho ChiTietBaoCaoTinhTrangBo

**Comment by vstrunghieu** [comment]
Upload len GitHub, chuyen trang thai Issue sang close

**Comment by 4azuo** [comment]
ok, closed!
