### ISSUE TITLE
table ChiTietBaoCaoXuat

### ISSUE THREAD

**Issue by 4azuo** [15HCB2-Wind/DoAn-PT-HTTT-HD#17]

**Comment by vstrunghieu** [comment]
Đã xong DataAccess + Data Service cho ChiTietBaoCaoXuat

**Comment by vstrunghieu** [comment]
Đã xong DataAccess + Data Service cho ChiTietBaoCaoXuat

**Comment by vstrunghieu** [comment]
Upload len GitHub, chuyen trang thai Issue sang close

**Comment by 4azuo** [comment]
ok, closed!
