### ISSUE TITLE
BackEnd-Fin: Chi nhánh

### ISSUE THREAD

**Issue by 4azuo** [15HCB2-Wind/DoAn-PT-HTTT-HD#56]
Thêm/Xóa/Sửa chi nhánh.
Chọn/Thay đổi quản lý cho chi nhánh.
Cập nhật tình trạng chi nhánh.

**Comment by vstrunghieu** [comment]
Hoàn Thành Thêm/Xóa/Sửa Chi nhánh

**Comment by vstrunghieu** [comment]
Fix Lỗi và hoàn thành

**Comment by 4azuo** [comment]
ok, close!
