### ISSUE TITLE
FrontEnd-Base: Chi nhánh

### ISSUE THREAD

**Issue by 4azuo** [15HCB2-Wind/DoAn-PT-HTTT-HD#57]
Thêm/Xóa/Sửa chi nhánh.
Chọn/Thay đổi quản lý cho chi nhánh.
Cập nhật tình trạng chi nhánh.

**Comment by vstrunghieu** [comment]
Hoàn thành load danh sách chi nhánh

**Comment by 4azuo** [comment]
ok, close!
